[package]
name = "rebook-formats"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyrender.workspace = true
arc-swap = "1.9.2"
anyrender_vello_cpu = { version = "0.17.0", default-features = false }
base64.workspace = true
crc32fast.workspace = true
encoding_rs.workspace = true
flate2.workspace = true
hayro.workspace = true
image.workspace = true
kurbo.workspace = true
libchm.workspace = true
quick-xml.workspace = true
rebook-html = { path = "../html" }
rebook-layout = { path = "../layout" }
rebook-renderer = { path = "../renderer" }
rebook-publication = { path = "../publication" }
roxmltree.workspace = true
scraper.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
zip.workspace = true

[lints]
workspace = true
