[package]
name = "rebook-formats"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
crc32fast.workspace = true
encoding_rs.workspace = true
flate2.workspace = true
hayro.workspace = true
image.workspace = true
kurbo.workspace = true
libchm.workspace = true
quick-xml.workspace = true
rebook-html = { path = "../html" }
rebook-publication = { path = "../publication" }
roxmltree.workspace = true
scraper.workspace = true
sha2.workspace = true
thiserror.workspace = true
zip.workspace = true

[lints]
workspace = true
