[package]
name = "rebook-gpui-renderer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
gpui.workspace = true
image.workspace = true
rebook-layout = { path = "../layout" }
rebook-publication = { path = "../publication" }

[lints]
workspace = true
